user_provided_deployment_id: datarobot/max.dugan-knight/my-awesome-deployment-id
user_provided_model_id: datarobot/max.dugan-knight/model-unique-id-1
prediction_environment_name: https://cfds-ccm-prod.orm.datarobot.com